var Events=Events||{};
/* Events :  */
Events = {
  // draw-back
  'DRAWBACK-LIST-DATA-UPDATE-COMPLETE'   : 'DRAWBACK-LIST-DATA-UPDATE-COMPLETE',
  'DRAWBACK-DETAIL-DATA-UPDATE-COMPLETE' : 'DRAWBACK-DETAIL-DATA-UPDATE-COMPLETE',
  'DRAWBACK-COMPLETE'                    : 'DRAWBACK-COMPLETE',
  // suspension
  'GET-MEMBERS-COMPLETE'                 : 'GET-MEMBERS-COMPLETE',
  'POST-SUSPENSION-COMPLETE'             : 'POST-SUSPENSION-COMPLETE'
};
